animal = " chanCHito feliz "
print(animal.upper())
print(animal.lower())
print(animal.capitalize())
print(animal.title())
print(animal.strip())
print(animal.lstrip())
print(animal.rsplit())
print(animal.find("cH"))
print(animal.replace("nCH", "j"))
print("nCH" in animal)
print("nCH" not in animal)
